---
- hosts: all
  tasks:

  - name: "System: Setup docker repository key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "System: Setup stable docker repository"
    apt_repository:
      filename: 'docker-ce'
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

  - name: "System: Install Docker engine"
    apt:
      name: docker-ce=17.03.1~ce-0~ubuntu-xenial
      state: present
      update_cache: yes

  - name: "System: Install pip package"
    apt:
      name: python-setuptools
      state: present
      update_cache: yes

  - name: "System: Install docker-py pip package"
    easy_install:
      name: docker-py
