---
- hosts: all
  tasks:

  - name: hadoop-zkfc
    docker_container:
      name: hadoop-zkfc
      image: express42/hadoop-zkfc
      network_mode: host
      restart: no
      pull: true
      #restart_policy: on-failure
      env_file: /etc/hadoop.env
    when: journal_node_active or journal_node_standby
