---
- hosts: all
  tasks:

  - name: "Docker Hadoop: Setup hadoop-journalnode"
    docker_container:
      name: hadoop-journalnode
      image: express42/hadoop-journalnode
      network_mode: host
      restart: yes
      pull: true
      restart_policy: on-failure
      volumes:
        - /mnt/hadoop-journal:/hadoop/dfs/journal
        - /mnt/hadoop-data:/hadoop/dfs/data
      env_file: /etc/hadoop.env
