---
- hosts: all
  tasks:

  - name: Update /etc/hosts from inventory
    lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
    with_items: '{{ groups.all }}'
    tags:
      - hosts

  - name: Update /etc/hosts from string
    lineinfile: dest=/etc/hosts line='{{hostvars[item].ansible_default_ipv4.address}} express42' state=present
    with_items: '{{ groups.all }}'
    tags:
      - hosts

  - name: create env file
    copy:
      dest: /etc/hadoop.env
      content: |
        CLUSTER_NAME=express42
        CORE_CONF_fs_defaultFS=hdfs://express42
        CORE_CONF_hadoop_http_staticuser_user=root
        CORE_CONF_dfs_journalnode_edits_dir=/hadoop/dfs/journal
        CORE_CONF_ha_zookeeper_quorum=node1:2181,node2:2181,node3:2181
        HDFS_CONF_dfs_ha_fencing_methods=sshfence(root:2122)
        HDFS_CONF_dfs_ha_fencing_ssh_private___key___files=/root/.ssh/id_rsa
        HDFS_CONF_dfs_nameservices=express42
        HDFS_CONF_dfs_ha_namenodes_express42=node1,node2
        HDFS_CONF_dfs_namenode_rpc___address_express42_node1=node1:8020
        HDFS_CONF_dfs_namenode_rpc___address_express42_node2=node2:8020
        HDFS_CONF_dfs_namenode_http___address_express42_node1=node1:50070
        HDFS_CONF_dfs_namenode_http___address_express42_node2=node2:50070
        HDFS_CONF_dfs_namenode_shared_edits_dir=qjournal://node1:8485;node2:8485;node3:8485/express42
        HDFS_CONF_dfs_client_failover_proxy_provider_mycluster=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
        HDFS_CONF_dfs_ha_automatic___failover_enabled=true

- include: hadoop-zookeeper.yml
- include: hadoop-journalnode.yml
- include: hadoop-namenode.yml
- include: hadoop-zkfc.yml
- include: hadoop-datanode.yml
