---
- hosts: all
  tasks:

  - name: "Docker Hadoop: Setup hadoop-namenode-active"
    docker_container:
      name: hadoop-namenode
      image: express42/hadoop-namenode
      network_mode: host
      #restart: yes
      pull: true
      restart_policy: on-failure
      volumes:
        - /mnt/hadoop-namenode:/hadoop/dfs/name
      env_file: /etc/hadoop.env
    when: journal_node_active

  - name: hadoop-namenode-standby
    docker_container:
      name: hadoop-namenode
      image: express42/hadoop-namenode
      network_mode: host
      restart: no
      pull: true
      restart_policy: on-failure
      volumes:
        - /mnt/hadoop-namenode:/hadoop/dfs/name
      env:
        NN_STANDBY=true
      env_file: /etc/hadoop.env
    when: journal_node_standby
