---
- hosts: all
  tasks:

  - name: Update /etc/hosts from inventory
    lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
    with_items: '{{groups.all}}'
    tags:
      - hosts

  - name: create env file
    copy:
      dest: /etc/hadoop.env
      content: |
        CORE_CONF_fs_defaultFS=hdfs://express42:8020
        CORE_CONF_hadoop_http_staticuser_user=root

- include: hadoop-namenode.yml
- include: hadoop-datanode.yml
