---
- hosts: all
  tasks:

  - name: hadoop-namenode
    docker_container:
      name: hadoop-namenode
      image: express42/hadoop-namenode
      network_mode: host
      restart: yes
      recreate: yes
      restart_policy: on-failure
      volumes:
        - /mnt/hadoop_namenode:/hadoop/dfs/name
      env:
        CLUSTER_NAME: e42cluster
      env_file: /etc/hadoop.env
