---
- hosts: all
  tasks:

  - name: "Docker Hadoop: Setup hadoop-datanode"
    docker_container:
      name: hadoop-datanode
      image: express42/hadoop-datanode
      network_mode: host
      restart: yes
      pull: true
      #restart_policy: on-failure
      volumes:
        - /mnt/hadoop-data:/hadoop/dfs/data
      env_file: /etc/hadoop.env
