---
- hosts: all
  tasks:

  - name: "Docker Hadoop: Setup hadoop-zkfc"
    docker_container:
      name: hadoop-zkfc
      image: express42/hadoop-zkfc
      network_mode: host
      #restart: yes
      pull: true
      #restart_policy: on-failure
      env_file: /etc/hadoop.env
    when: journal_node_active or journal_node_standby
