---
converged: true
created: true
default_platform: null
default_provider: null
driver: vagrant
driver_config:
  current_platform: xenial64
  current_provider: parallels
  instances:
  - interfaces:
    - auto_config: true
      network_name: private_network
      type: dhcp
    name: common
    options:
      append_platform_to_hostname: false
    vm_name: common
  platforms:
  - box: parallels/ubuntu-16.04
    name: xenial64
  providers:
  - name: parallels
    options:
      cpus: 2
      memory: 4096
    type: parallels
  raw_config_args:
  - ssh.insert_key = false
hosts:
  common:
    groups: []
multiple_platforms: null
